# Generated by Django 3.0.8 on 2020-07-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('barcode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('nutriscore_grade', models.CharField(max_length=4)),
                ('product_description', models.TextField()),
                ('off_url', models.CharField(max_length=255)),
                ('categories', models.ManyToManyField(to='core.Category')),
            ],
        ),
    ]
