# Generated by Django 3.0.8 on 2020-07-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200705_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='substitutes',
            field=models.ManyToManyField(related_name='_product_substitutes_+', to='core.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(to='core.Store'),
        ),
    ]
