# Generated by Django 3.0.8 on 2020-07-14 05:59

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200705_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('product_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='substitutes',
            field=models.ManyToManyField(to='core.Product'),
        ),
    ]
